// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBPWiqTJoEyGI5GdtWAIm4sYXpkhA8KON8',
    appId: '1:173828986729:android:1bde44f756a5f50f4c8ff8',
    messagingSenderId: '173828986729',
    projectId: 'we-chat-7b125',
    storageBucket: 'we-chat-7b125.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD77gAIp1qv7wKfogrPbfnV2Ntf-aIsF18',
    appId: '1:173828986729:ios:118f0f944c609df14c8ff8',
    messagingSenderId: '173828986729',
    projectId: 'we-chat-7b125',
    storageBucket: 'we-chat-7b125.appspot.com',
    androidClientId: '173828986729-icdk2kqm9t193sgki9lnfm8stsbjf9t3.apps.googleusercontent.com',
    iosClientId: '173828986729-e7nonfj85788m87cq8sldrtv3bg3g83q.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );
}
